# Generated by Django 4.2 on 2024-09-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.CharField(choices=[('juan', 'Juan'), ('maria', 'Maria')], max_length=5)),
                ('receptor', models.CharField(choices=[('juan', 'Juan'), ('maria', 'Maria')], max_length=5)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
